---
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - verifyConditionsCmd: "echo \"Verified!\""
      publishCmd: "echo \"${nextRelease}\" > foo"

branches:
  - name: main
    # prerelease: true
