[package]
name = "rust-integrity-playground"
version = "0.1.1"
edition = "2018"
authors = ["Kristof Mattei"]
description = "Rust integrity playground"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
clippy = { version = "0.0.302", optional = false }
rustfmt = { version = "0.10.0", optional = false }

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-for-all", "run-cargo-test", "run-cargo-check", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
reqwest = { version = "0.11.5", features = ["json"] }
serde_json = "1.0.68"
serde = { version = "1.0.130", features = ["derive"] }
futures = "0.3.17"
tokio = { version = "1.12.0", features = ["full"] }
log = "0.4.14"
env_logger = "0.9.0"
serde_yaml = "0.8.21"
structopt = "0.3.23"

# We compile the docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
openssl = { version = "0.10.36", features = ["vendored"] }

