name: CI & PR

on:
  pull_request:
    branches:
      - main
  # I need to find out a way to kill the push triggered event when there's a matching pull_request trigger
  # push:
  #   branches-ignore:
  #     - main
env:
  CARGO_TERM_COLOR: always
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

concurrency:
  group: pr-${{ github.event.number }} # ${{ github.head_ref }}${{ github.ref }} <- when we expand to non-PRs
  cancel-in-progress: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      # code: ${{ steps.filter.outputs.code }}
      code: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: ./.github/actions/dorny/paths-filter # since this is a submodule, it depends on which version is pinned
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            code:
              - "src/*"
              - "src/**/*"
              - "TAG"
              - "*.toml"
              - Dockerfile
              - "tests/*"
              - "tests/**/*"

  cargo-build:
    name: Cargo build
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (needs.changes.outputs.code == 'true')

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up toolchain
        uses: ./.github/actions/actions-rs/toolchain # since this is a submodule, it depends on which version is pinned
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Dump CARGO_HOME # we're going to use this to cache Cargo, same for the Docker container
        run: |
          ls $HOME/.cargo

      - name: Test
        uses: ./.github/actions/actions-rs/cargo
        with:
          command: test
          args: --verbose

  cargo-test:
    name: Cargo test
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (needs.changes.outputs.code == 'true')

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up toolchain
        uses: ./.github/actions/actions-rs/toolchain # since this is a submodule, it depends on which version is pinned
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        uses: ./.github/actions/actions-rs/cargo
        with:
          command: test
          args: --verbose


  cargo-fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (needs.changes.outputs.code == 'true')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up toolchain
        uses: ./.github/actions/actions-rs/toolchain # since this is a submodule, it depends on which version is pinned
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Fmt
        uses: ./.github/actions/actions-rs/cargo
        with:
          command: fmt
          args: --all -- --check

  cargo-clippy-and-report:
    name: Run Clippy
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (needs.changes.outputs.code == 'true')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up toolchain
        uses: ./.github/actions/actions-rs/toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      # we may want to remove this if clippy-check also reports to the
      # logs in GitHub actions
      - name: Clippy
        uses: ./.github/actions/actions-rs/cargo
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features -- -D warnings

  # TODO code coverage here

  publish:
    name: Build docker container and publish
    needs:
      - cargo-build
      - cargo-test
      - cargo-fmt
      - cargo-clippy-and-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO validate no changes between github.pull_request.head.sha and the actual current sha (representing the hypothetical merge)

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          # push the created docker image when it's the tip of a PR
          # this container is THE artifact, and we will re-tag it
          # once the PR has been accepted
          push: |
            (github.repository == 'Kristof-Mattei/rust-integrity-playground')
            && (github.event_name == 'pull_request')
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
