name: Dump

# **What it does**: This lints our yaml files in the docs repository.
# **Why we have it**: We want some level of consistent formatting for YAML files.
# **Who does it impact**: Docs engineering, docs content.

on:
  push:
    branches:
      - main

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: echo "${{ toJSON(github) }}"
