name: Tag containers

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

# Controls when the workflow will run
on:
  # Triggers the workflow pushes to main, which by control in GitHub should only be PR merges
  pull_request:
    branches: [ main ]
    types: [ closed ]
  push:
    tags:
      - "v**"

  # I don't think we need this
  # workflow_dispatch:

env:
  OLD_TAG: ""
  FULL_IMAGE_NAME: ""
  CRANE_DOCKER_CONFIG_VOLUME: ""

jobs:
  retag-containers:
    name: Retag the containers
    runs-on: ubuntu-latest
    steps:

      - name: Set up Crane volume and define env variables
        shell: bash
        run: |

          CRANE_DOCKER_CONFIG_VOLUME="crane_docker_config"
          docker volume create ${CRANE_DOCKER_CONFIG_VOLUME};

          # for security purposes let's create a volume for .docker in crane
          CRANE_DOCKER_CONFIG_LOCATION="/${CRANE_DOCKER_CONFIG_VOLUME}"

          # generalize the mount config
          CRANE_DOCKER_CONFIG_VOLUME_MOUNT="type=volume,src=${CRANE_DOCKER_CONFIG_VOLUME},dst=${CRANE_DOCKER_CONFIG_LOCATION}"

          echo "CRANE_DOCKER_CONFIG_VOLUME=${CRANE_DOCKER_CONFIG_VOLUME}" >> ${GITHUB_ENV}
          echo "CRANE_DOCKER_CONFIG_LOCATION=${CRANE_DOCKER_CONFIG_LOCATION}" >> ${GITHUB_ENV}
          echo "CRANE_DOCKER_CONFIG_VOLUME_MOUNT=${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" >> ${GITHUB_ENV}

          # prepare the volume so that crane can write to is
          # note that the ${} passed in via sh are rendered before we run the container
          # so it just gets an actual string
          docker run \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            alpine:latest \
            sh -c "chmod 700 ${CRANE_DOCKER_CONFIG_LOCATION} && chown 65532:65532 ${CRANE_DOCKER_CONFIG_LOCATION}"

      - name: Set full image name
        shell: bash
        run: |

          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Crane login
        shell: bash
        run: |

          docker run \
            --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            gcr.io/go-containerregistry/crane:latest \
            auth login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Find all tags for ${{ env.FULL_IMAGE_NAME }}
        shell: bash
        id: find-existing-tags
        run: |

          (
            docker run \
              --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
              --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
              --rm \
              gcr.io/go-containerregistry/crane:latest \
              ls ${FULL_IMAGE_NAME}
          ) >> existing_tags

          echo "::set-output name=tags::$(cat existing_tags | jq --raw-input . | jq --slurp . | jq --compact-output)"

      - name: Find out if the incoming PR has a docker image in the form of :pr-<number>-latest
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_TAG: "pr-${{ github.event.number }}-latest"
        shell: bash
        run: |
          suffix="retag"

          # search for the tag, and get the cargo2
          # it can only happen once
          # we need the || true because
          # otherwise grep returns exit code 1 and github actions then dies
          pr_tag_found=$(cat existing_tags | grep -c "^${PR_TAG}\$") || true

          if [ $pr_tag_found -eq 1 ]
          then
            echo "Incoming PR produced a Docker image"
            echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}

            suffix="actual"
          fi

          echo "NEW_TAG=sha-${{ github.sha }}-${suffix}" >> ${GITHUB_ENV}

      - name: Find the container to which we'll apply our new tag
        if: ${{ env.OLD_TAG == '' }}
        env:
          SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.sha }}
        shell: bash
        run: |

          # this step gets executed if we have a PR that didn't build a container (env.OLD_TAG empty)
          # or always in the case of an incoming tag
          old_tag=$(cat existing_tags | grep "^sha-${SHA}-.*\$")

          echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}

      - name: New tag for tags
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        shell: bash
        run: |
          # tags: |
          #   # output 0.1.2
          #   type=semver,pattern=v{{version}}
          #   # output 0.1
          #   type=semver,pattern=v{{major}}.{{minor}}
          #   # disabled if major zero
          #   type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

          # the new docker tag, for incoming tags
          echo "NEW_TAG=${{ github.ref_name }}" >> ${GITHUB_ENV}

      - name: Actually re-tag the container
        shell: bash
        run: |

          echo "tag \"${FULL_IMAGE_NAME}:${OLD_TAG}\" ${NEW_TAG}"

          docker run \
            --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            gcr.io/go-containerregistry/crane:latest \
            tag "${FULL_IMAGE_NAME}:${OLD_TAG}" ${NEW_TAG}

      - name: Cleanup!
        if: ${{ always() }}
        shell: bash
        run: |
          docker volume rm ${{ env.CRANE_DOCKER_CONFIG_VOLUME }}

