name: Tag containers

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  # Triggers the workflow pushes to main, which by disabling pushes to `main` in GitHub should only be PR merges
  push:
    branches: [main]
    tags:
      - "v**"
  # note how we're not doing
  # pull_request_target, as it isn't what we need.
  # we need the push event to make it show up nicely in the UI
  # this however brings a whole new slew of problems, like how do we identify the
  # incoming PR's artifacts?
  # well, we set a tag on that PR's artifact, in the form of
  # pr-{head_of_pr}-{pr_head_of_main}
  # when with git rev-parse HEAD^2 we can find the incoming PR's head
  # Problem solved

  # We may want this to explicitly cut a release?
  # workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  retag-containers:
    name: Retag the containers
    runs-on: ubuntu-latest
    needs:
      - should-workflow-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find out the SHA of the tip of the incoming PR
        shell: bash
        run: |
          incoming_pr_head_commit=${git rev-parse HEAD^2}
          echo "The head of the incoming PR is ${incoming_pr_head_commit}"
          echo "The base of the incoming PR is ${{ github.event.before }} (from GitHub)"
          echo "The base of the incoming PR is ${{ git rev-parse HEAD^ }} (from rev-parse)"
          echo "INCOMING_PR_HEAD_COMMIT=${incoming_pr_head_commit} >> ${GITHUB_ENV}


      - name: Set up Crane volume and define env variables
        shell: bash
        run: |

          # for security purposes let's create a volume for .docker in crane
          CRANE_DOCKER_CONFIG_VOLUME="crane_docker_config"

          CRANE_DOCKER_CONFIG_LOCATION="/.docker_config"

          # this volume will hold the the docker.json
          docker volume create ${CRANE_DOCKER_CONFIG_VOLUME};

          # generalize the mount config, which we'll export later too
          CRANE_DOCKER_CONFIG_VOLUME_MOUNT="type=volume,src=${CRANE_DOCKER_CONFIG_VOLUME},dst=${CRANE_DOCKER_CONFIG_LOCATION}"

          # prepare the volume so that crane can write to is
          # note that the ${} passed in via sh are rendered before we run the container
          # so it just gets an actual string
          docker run \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            alpine:latest \
            sh -c "chmod 700 ${CRANE_DOCKER_CONFIG_LOCATION} && chown 65532:65532 ${CRANE_DOCKER_CONFIG_LOCATION}"

          # export the variables for future operations
          echo "CRANE_DOCKER_CONFIG_VOLUME=${CRANE_DOCKER_CONFIG_VOLUME}" >> ${GITHUB_ENV}
          echo "CRANE_DOCKER_CONFIG_LOCATION=${CRANE_DOCKER_CONFIG_LOCATION}" >> ${GITHUB_ENV}
          echo "CRANE_DOCKER_CONFIG_VOLUME_MOUNT=${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" >> ${GITHUB_ENV}

      - name: Set full image name
        shell: bash
        run: |

          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Crane login
        shell: bash
        run: |

          docker run \
            --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            gcr.io/go-containerregistry/crane:latest \
            auth login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Find all tags for ${{ env.FULL_IMAGE_NAME }}
        shell: bash
        run: |

          docker run \
            --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
            --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
            --rm \
            gcr.io/go-containerregistry/crane:latest \
            ls ${FULL_IMAGE_NAME} >> existing_tags

          echo "These are the existing tags on ${FULL_IMAGE_NAME}"
          cat existing_tags

      - name: Check if the incoming PR has a Docker container, which will be our old tag
        env:
          PR_TAG: "pr-${{ github.event.before }}-with-${{ env.INCOMING_PR_HEAD_COMMIT }}"
        shell: bash
        run: |
          # search for the tag, there can only be zero or one match
          # we need the || true because otherwise grep returns exit code 1 and github actions then dies
          pr_tag_found=$(cat existing_tags | grep -c "^${PR_TAG}\$") || true

          if [ $pr_tag_found -eq 1 ]
          then
            echo "Incoming PR produced a Docker image"
            echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}
            echo "SUFFIX=actual" >> ${GITHUB_ENV}
          else
            echo "SUFFIX=retag" >> ${GITHUB_ENV}
          fi

      - name: Find the old tag if the PR didn't produce a container.
        # If we don't have an old tag, then the incoming PR didn't produce a container.
        # In which case we're going to find the container referenced to the base commit, and add our current sha as a tag to it
        if: ${{ env.OLD_TAG == '' }}
        shell: bash
        run: |
          old_tag=$(cat existing_tags | grep "^sha-${{ github.event.before }}-.*\$") # .* is actual or retag

          echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}

      - name: Set the new TAGs
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
            # type=semver,pattern=v{{version}}
            # type=semver,pattern=v{{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
            # type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          tags: |
            type=sha,format=long,prefix=sha-,suffix=-${{ env.SUFFIX }}

      - name: Actually re-tag the container
        shell: bash
        run: |
          echo "${{ steps.meta.outputs.tags }}" | while read new_tag
          do
            docker run \
              --env DOCKER_CONFIG=${CRANE_DOCKER_CONFIG_LOCATION} \
              --mount "${CRANE_DOCKER_CONFIG_VOLUME_MOUNT}" \
              --rm \
              gcr.io/go-containerregistry/crane:latest \
              cp "${FULL_IMAGE_NAME}:${OLD_TAG}" ${new_tag}
          done

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Cleanup!
        if: ${{ always() }}
        shell: bash
        run: |
          docker volume rm ${{ env.CRANE_DOCKER_CONFIG_VOLUME }}
