name: Tag event test

on:
  push:
    tags:
      - "v*"

  # I don't think we need this
  # workflow_dispatch:
jobs:
  dump:
    name: Dump
    runs-on: ubuntu-latest
    env:
      GITHUB: ${{toJson(github)}}
    steps:
      - name: Dump
        shell: bash
        run: |
          echo ${GITHUB}
