name: Lint Yaml

# **What it does**: This lints our yaml files in the docs repository.
# **Why we have it**: We want some level of consistent formatting for YAML files.
# **Who does it impact**: Docs engineering, docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97

      - name: Setup Node.js
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        shell: bash
        run: |
          npm ci --ignore-scripts

      - name: Run linter
        run: npx --no-install prettier -c "**/*.{yml,yaml}"
